module.exports = {
    contains: require('./arrays/contains'),
    every: require('./arrays/every'),
    filter: require('./arrays/filter'),
    first: require('./arrays/first'),
    flatMap: require('./arrays/flatMap'),
    groupBy: require('./arrays/groupBy'),
    grouped: require('./arrays/grouped'),
    groupedRight: require('./arrays/groupedRight'),
    include: require('./arrays/include'),
    indexOf: require('./arrays/indexOf'),
    isArray: require('./arrays/isArray'),
    joinPaths: require('./arrays/joinPaths'),
    last: require('./arrays/last'),
    map: require('./arrays/map'),
    max: require('./arrays/max'),
    min: require('./arrays/min'),
    range: require('./arrays/range'),
    reduce: require('./arrays/reduce'),
    remove: require('./arrays/remove'),
    some: require('./arrays/some')
};
