import jQuery from 'jquery'
import './proto/index'
import './deserialize'
import './findByName'
import './findByNames'
import './groupBy'
import './maxZIndex'
import './nextTick'
import './obj'
import './reclone'
import './reindexArrayParams'
import './reverse'
import './serializeObject'
import './some'
import './split'
import './supportsInputType'
import './xmlToString'

export default jQuery;
